-- Accounts
CREATE TABLE WalletAccounts (
    AccountId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    FullName VARCHAR2(100) NOT NULL,
    PhoneNumber VARCHAR2(20),
    PasswordHash VARCHAR2(256) NOT NULL,
    Balance NUMBER(18,2) DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bank Cards
CREATE TABLE BankCards (
    CardId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountId NUMBER REFERENCES WalletAccounts(AccountId),
    CardNumber VARCHAR2(16) NOT NULL,
    CardHolderName VARCHAR2(100),
    ExpiryDate DATE,
    CardType VARCHAR2(20),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transactions
CREATE TABLE Transaction (
    TransactionId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FromAccountId NUMBER REFERENCES WalletAccounts(AccountId),
    ToAccountId NUMBER REFERENCES WalletAccounts(AccountId),
    Amount NUMBER(18,2) NOT NULL,
    TransactionType VARCHAR2(20), -- "Transfer", "Deposit", "Withdrawal"
    Status VARCHAR2(20) DEFAULT 'Pending',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Beneficiaries
CREATE TABLE Beneficiaries (
    BeneficiaryId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountId NUMBER REFERENCES WalletAccounts(AccountId),
    Name VARCHAR2(100),
    WalletAddress VARCHAR2(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Notifications
CREATE TABLE Notifications (
    NotificationId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountId NUMBER REFERENCES WalletAccounts(AccountId),
    Message VARCHAR2(500),
    IsRead CHAR(1) DEFAULT 'N',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM WalletAccounts;
SELECT * FROM BankCards;
SELECT * FROM Transaction;
SELECT * FROM Beneficiaries;
SELECT * FROM Notifications;
